-- Seed data for initial assets and liquidity pools
-- Generated for equitx-project

-- Insert default assets
INSERT INTO asset (symbol, feed_address, price, last_xlm_price, created_at, updated_at)
VALUES 
  ('xBTC', 'CCYOZJCOPG34LLQQ7N24YXBM7LL62R7ONMZ3G6WZAAYPB5OYKOMJRN63', '30000.00', '0.12', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xETH', 'CCYOZJCOPG34LLQQ7N24YXBM7LL62R7ONMZ3G6WZAAYPB5OYKOMJRN63', '2000.00', '0.12', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xUSDT', 'CCYOZJCOPG34LLQQ7N24YXBM7LL62R7ONMZ3G6WZAAYPB5OYKOMJRN63', '1.00', '0.12', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xXRP', 'CCYOZJCOPG34LLQQ7N24YXBM7LL62R7ONMZ3G6WZAAYPB5OYKOMJRN63', '0.50', '0.12', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xSOL', 'CCYOZJCOPG34LLQQ7N24YXBM7LL62R7ONMZ3G6WZAAYPB5OYKOMJRN63', '25.00', '0.12', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xADA', 'CCYOZJCOPG34LLQQ7N24YXBM7LL62R7ONMZ3G6WZAAYPB5OYKOMJRN63', '0.30', '0.12', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xDOT', 'CCYOZJCOPG34LLQQ7N24YXBM7LL62R7ONMZ3G6WZAAYPB5OYKOMJRN63', '5.00', '0.12', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  -- Special XLM asset for price tracking
  ('XLM', 'CCYOZJCOPG34LLQQ7N24YXBM7LL62R7ONMZ3G6WZAAYPB5OYKOMJRN63', '0.12', '0.12', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insert corresponding liquidity pools
-- Note: Using placeholder values for pool_address and wasm_hash, replace with actual values from your config
INSERT INTO liquidity_pools (asset_id, pool_address, minimum_collateralization_ratio, mercury_wasm_hash, created_at, updated_at)
SELECT 
  a.id,
  CASE a.symbol
    WHEN 'xBTC' THEN 'CCY5XML5KDGAMVKFFVKZDHPTYH2U6GCCLXDNJKIYDBLJGK5PCJVEQTNQ'
    WHEN 'xETH' THEN 'CACG7ZCHMXHXIMZN5DDNCVA45VCVA4JQIN3JJNMOFNY3UZLZHZVKYRII'
    WHEN 'xUSDT' THEN 'CCKR63NJ2UP55LGYI4XG2JBMZBLQYPOOMURKNEXCWA7HLVSJMUZTWOZY'
    WHEN 'xXRP' THEN 'CAQ2GB7SJVPHY5QIEWVJLQ64SFSUTQFGLT6JRTS7CTRTXEFRE3GBOGBV'
    WHEN 'xSOL' THEN 'CCDSOHTUP54GTP3CN4PCNI3GPP5ICZNZPLUIKVAEMGOJVNAQBAPX3GNX'
    WHEN 'xADA' THEN 'CDWUZOKTVRABQUCXOLBRDBLCLSKJNPNHYKOUG6GQJAYF23WMLOCJCMNY'
    WHEN 'xDOT' THEN 'CDY6EUFFLVUC2F2LBJ5PDCIXBDXVXRMYXSVZRBFNRA7WFFRDS6XBTLUJ'
  END as pool_address,
  150 as minimum_collateralization_ratio,
  '14d5bbeabb4dd7603b4f47bfaf4f2703' as mercury_wasm_hash,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
FROM asset a
WHERE a.symbol != 'XLM'; -- Exclude XLM as it doesn't get a liquidity pool
